### ISSUE TITLE
[FlexFields] Rule set does not seem to work correctly

### ISSUE THREAD

**Issue by houtaiwong-toast** [contentful/marketplace-partner-apps#702] opened 2024-01-12 17:24 UTC
Hello, I'm testing out your app in an test environment and I can't seem to get it to function correctly at all.

**Describe the bug**
Adding rules does not show and hide the correct fields when changing "layout".

**To Reproduce**
I've attached a video file of our screen recording of the issue. 

**Expected behavior**
When rules are added the correct fields show/hide when switching between "layout" field values. 

https://github.com/contentful/marketplace-partner-apps/assets/55763151/2e6b1c33-e5be-4e36-a01f-1341ba6e9a7a

**Comment by lilbitner** [comment] 2024-01-12 22:00
Hi @houtaiwong-toast, thank you for raising this issue! Currently a constraint with the app framework is that you must refresh the Contentful web app once a change to the app configuration has been made. Do you mind trying to refresh the web app after setting the rules on the configuration page, and letting me know if this resolves the issue? If not, we will certainly look into it.

**Comment by vipulchadda** [comment] 2024-01-16 17:23
@houtaiwong-toast It looks like not all fields are showing up in the FlexFields editor. Can you share how the content type is set up and also how this looks in the default Contentful editor so that we can reproduce and debug this further. Thanks.

**Comment by sizzle168** [comment] 2024-01-23 13:35
Not sure if it's the same issue but it at least looks similar to this one here.
I created 5 simple rules that check if a short text field contains a specific value and if so, hide another field. But these rules only work partly. When I look into the browsers dev tools I can see that https://api.contentful.com blocks some calls with HTTP 429 Too many requests. Could this be the reason and if so, what can I do about it?

**Comment by sizzle168** [comment] 2024-02-06 13:18
@lilbitner @vipulchadda Do you think that @houtaiwong-toast's problem is also because of the contentful rate limiting?

**Comment by vipulchadda** [comment] 2024-02-06 20:57
@sizzle168 I don't think there should be any issues with rate limiting. Would you be able to share more details about the fields you are using and the rules that are set. This will allow us to reproduce this issue and dig into this further.

**Comment by sizzle168** [comment] 2024-02-07 12:41
This is how the content type looks:
<img width="806" alt="Content Type" src="https://github.com/contentful/marketplace-partner-apps/assets/19364321/e41dc314-ccef-4948-9dab-b3b2c025f522">

These are the configured rules:
<img width="1310" alt="Rules" src="https://github.com/contentful/marketplace-partner-apps/assets/19364321/46fd7867-7291-40e1-8ecd-1c7df3053fbb">

I tested it again today and it still failed. So I checked the rules again and recognized that the non-working rules were lacking this "(Same Entry)" appendage. So I removed and recreated these rules and now it works perfectly. I also can't find any 429 responses anymore in the dev tools' network tab. 

Any idea?

**Comment by sizzle168** [comment] 2024-02-07 13:00
Ok I found out how to break it again!

I added new fields to the content type as below:
<img width="841" alt="image" src="https://github.com/contentful/marketplace-partner-apps/assets/19364321/b859c8d0-48b0-4c01-9f35-644fbaf63fb6">

Then I changed a rule to also hide these new fields. After saving the rule configuration, the "(Same Entry)" appendage disappeared and the rule didn't work anymore.
<img width="1301" alt="image" src="https://github.com/contentful/marketplace-partner-apps/assets/19364321/53b7e529-0d4c-4950-b918-e873ee68dfac">


Does that help you?

**Comment by vipulchadda** [comment] 2024-02-08 22:16
Oh, I guess that might be the issue. I think there was a change to allow for any reference to the same content type. So the rules without `(Same Entry)` would be invalid as you dont have any reference fields. Can you try to recreate/update that rule to make sure it uses `(Same Entry)` value

**Comment by sizzle168** [comment] 2024-02-12 12:35
Yes, recreating the rule works, updating the rule unfortunately not. And recreating the rule everytime a newly added field needs to be considered by the rule, is not an option for us.

**Comment by vipulchadda** [comment] 2024-02-12 15:49
You should not have to recreate rules again all the time. This was due to 1 fix that was made to make sure this scenario works. Once you have fixed/recreated all existing rules (it should now say `(SameEntry)`), you will not need to recreate the rules. Just editing them should work properly

**Comment by sizzle168** [comment] 2024-02-12 18:51
That's not possible. Please, see my video. When editing a rule (even without changing anything), the rule will be broken after saving. Rules that no longer work can be recognized by the missing entry (Same Entry)

https://github.com/contentful/marketplace-partner-apps/assets/19364321/4138e254-b05b-41ef-a85d-3045521071e6

**Comment by vipulchadda** [comment] 2024-02-12 20:02
Oh, ok. Thanks for clarifying. Will work on fixing this and let you know once it is fixed.

**Comment by sizzle168** [comment] 2024-02-13 08:17
Thank you!

**Comment by vipulchadda** [comment] 2024-02-27 18:35
@lilbitner would you be able to help with the PR raised to fix this issue (https://github.com/contentful/marketplace-partner-apps/pull/919)

**Comment by whitelisab** [comment] 2024-02-28 14:52
@vipulchadda I'll be taking a look at your PRs today

**Comment by whitelisab** [comment] 2024-02-28 16:53
@houtaiwong-toast @sizzle168 I merged in @vipulchadda's fix and it is now deployed to production. Can you please verify that this issue is now resolved? Thank you!

**Comment by sizzle168** [comment] 2024-02-29 12:12
It's resolved! Thank's!

**Comment by whitelisab** [comment] 2024-02-29 15:41
> It's resolved! Thank's!

Great, thanks for confirming! I'll close this issue now.

**Closed by whitelisab** 2024-02-29 15:41 UTC
